### ISSUE TITLE
Negative offset in ScrollingPagerIndicator.onPageScrolled(int page, float offset)

### ISSUE THREAD

**Issue by cordel** [TinkoffCreditSystems/ScrollingPagerIndicator#4]
So it seems like if you are scrolling your viewpager slides too fast it's possible to get a negative offset 
value in `ScrollingPagerIndicator.onPageScrolled(int page, float offset)`. Although ` ViewPager.onPageScrolled` claims that possible value belongs to [0, 1).

btw by scrolling fast I mean using emulator and arrow keys to scroll. 

<img width="712" alt="screen shot 2018-02-20 at 19 46 22" src="https://user-images.githubusercontent.com/4090942/36436973-ca4e2438-1676-11e8-8b81-c6bbc76c51cd.png">

**Comment by N-Olifer** [comment]
Thank you for report! This was fixed in [1.0.2 version](https://github.com/TinkoffCreditSystems/ScrollingPagerIndicator/releases/tag/1.0.2).
