### ISSUE TITLE
Add detach from method

### ISSUE THREAD

**Issue by MRezaNasirloo** [TinkoffCreditSystems/ScrollingPagerIndicator#9]
Hi, it's a nice and simple to use library, good job there.

I'm having a situation where I need to detach the indicator from my recycler view or otherwise it will leak the whole activity. It would be nice to have detach methods to avoid any potential memory leak.

Thanks

**Comment by N-Olifer** [comment]
Hi! I have added ```detachFromPager``` method in version 1.0.4.
